"use client";

import React, { useEffect, useMemo, useState } from "react";

type IndustryGroups = Record<string, string[]>;

function hashToHue(str: string) {
  let h = 0;
  for (let i = 0; i < str.length; i++) h = (h * 31 + str.charCodeAt(i)) >>> 0;
  return h % 360;
}

function themeForKey(key: string) {
  const hue = hashToHue(key.toLowerCase());
  return {
    bg: `hsla(${hue}, 70%, 96%, 1)`,
    border: `hsla(${hue}, 55%, 80%, 1)`,
    chipBg: `hsla(${hue}, 60%, 98%, 1)`,
    chipBorder: `hsla(${hue}, 45%, 78%, 1)`,
    chipText: `hsla(${hue}, 30%, 22%, 1)`,
  };
}

function normalizeSymbol(s: string) {
  return String(s ?? "").trim().toUpperCase();
}


function cn(...xs: Array<string | false | null | undefined>) {
  return xs.filter(Boolean).join(" ");
}

function escapeRegExp(str: string) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function Highlight({ text, query }: { text: string; query: string }) {
  const q = query.trim();
  if (!q) return <>{text}</>;
  const re = new RegExp(escapeRegExp(q), "ig");
  const parts = text.split(re);
  const matches = text.match(re) || [];
  const out: any[] = [];
  for (let i = 0; i < parts.length; i++) {
    out.push(<span key={`p-${i}`}>{parts[i]}</span>);
    if (i < matches.length) {
      out.push(
        <mark
          key={`m-${i}`}
          className="rounded px-1 py-0.5 bg-yellow-100 text-yellow-900"
        >
          {matches[i]}
        </mark>
      );
    }
  }
  return <>{out}</>;
}


function Chevron({ open }: { open: boolean }) {
  return (
    <svg
      viewBox="0 0 20 20"
      className={cn("h-4 w-4 transition-transform", open ? "rotate-180" : "rotate-0")}
      fill="none"
      aria-hidden="true"
    >
      <path
        d="M5 7.5l5 5 5-5"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

function useScrollTopButton() {
  const [show, setShow] = React.useState(false);
  useEffect(() => {
    const onScroll = () => setShow(window.scrollY > 700);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);
  return show;
}



// ✅ HARD-CODED industry buckets (ALL 2000 tickers) generated from your uploaded Excel:
// watchlist_by_industry (2).xlsx → sheet "ALL"
// No fetch, no /public json, no 404.
const GROUPS: IndustryGroups = {
  "Agriculture/Forestry/Fishing": [
    "AGRO",
    "CALM",
    "VFF"
  ],
  "Communication Services (Telecom)": [
    "ADEA",
    "AMCX",
    "AMX",
    "ASTS",
    "CCOI",
    "CHTR",
    "CMCSA",
    "FOXA",
    "GLIBK",
    "GSAT",
    "GTN",
    "IHRT",
    "IHS",
    "IRDM",
    "LBRDK",
    "LUMN",
    "NMAX",
    "PSKY",
    "ROKU",
    "SATS",
    "SBGI",
    "SIRI",
    "SPIR",
    "SPOT",
    "SSP",
    "SURG",
    "T",
    "TDS",
    "TME",
    "TMUS",
    "TSAT",
    "TSQ",
    "TTGT",
    "UNIT",
    "UONEK",
    "VOD",
    "VSAT",
    "VZ",
    "WBD"
  ],
  "Construction": [
    "AMRC",
    "BBCP",
    "BZH",
    "DHI",
    "DY",
    "FIX",
    "GEO",
    "GRBK",
    "GVA",
    "LEN",
    "MTZ",
    "PHM",
    "STRL",
    "TOL",
    "TPC",
    "TPH"
  ],
  "Consumer (Retail)": [
    "AAP",
    "ABG",
    "ACI",
    "AEO",
    "AMZN",
    "ANF",
    "ARHS",
    "ARMK",
    "ASO",
    "BARK",
    "BBBY",
    "BBWI",
    "BBY",
    "BJ",
    "BKE",
    "BLMN",
    "BNED",
    "BROS",
    "BURL",
    "CAKE",
    "CAVA",
    "CBRL",
    "CHWY",
    "CMG",
    "COST",
    "CPNG",
    "CTRN",
    "CVNA",
    "CVS",
    "DBI",
    "DDL",
    "DG",
    "DKS",
    "DLTR",
    "DNUT",
    "DRI",
    "EAT",
    "ELA",
    "FIVE",
    "FLWS",
    "FND",
    "GAP",
    "GCO",
    "GCT",
    "GME",
    "GO",
    "HD",
    "JACK",
    "JD",
    "JMIA",
    "KMX",
    "KR",
    "KSS",
    "LESL",
    "LOW",
    "LUXE",
    "LVO",
    "M",
    "MCD",
    "OLLI",
    "PETS",
    "PLAY",
    "PLBY",
    "PLCE",
    "PTLO",
    "PZZA",
    "QVCGA",
    "REAL",
    "RH",
    "ROST",
    "RVLV",
    "SBUX",
    "SFIX",
    "SFM",
    "SG",
    "SHAK",
    "SIG",
    "STKS",
    "SVV",
    "TGT",
    "TJX",
    "TSCO",
    "TXRH",
    "ULTA",
    "URBN",
    "VIPS",
    "VRM",
    "VSCO",
    "W",
    "WEN",
    "WMT",
    "WOOF"
  ],
  "ETF (Commodity)": [
    "FCG",
    "GDX",
    "GDXJ",
    "GLD",
    "IAU",
    "SILJ",
    "SLV",
    "UNG",
    "USO",
    "XHB"
  ],
  "ETF (Index)": [
    "DIA",
    "DVY",
    "EDV",
    "EEM",
    "EFA",
    "EMB",
    "EWG",
    "EWJ",
    "EWZ",
    "FXI",
    "HYG",
    "IEF",
    "IVV",
    "IWM",
    "IYR",
    "LQD",
    "QQQ",
    "RSP",
    "SCHD",
    "SPY",
    "TLT",
    "VOO"
  ],
  "ETF (Leveraged/Inverse)": [
    "BDN",
    "BOIL",
    "BULL",
    "CCUP",
    "DRIP",
    "DUST",
    "ELDN",
    "FAS",
    "JDST",
    "KOLD",
    "LABD",
    "LABU",
    "MSTU",
    "MSTX",
    "MSTY",
    "MSTZ",
    "NUGT",
    "NVDL",
    "NVDS",
    "NVDU",
    "NVDX",
    "SMUP",
    "SOXL",
    "SOXS",
    "SPXL",
    "SPXS",
    "SPXU",
    "SQQQ",
    "SSO",
    "SVIX",
    "TECL",
    "TMF",
    "TNA",
    "TQQQ",
    "TSLL",
    "TSLQ",
    "TSLT",
    "TSLZ",
    "TZA",
    "UP",
    "UPRO",
    "UVIX",
    "UVXY",
    "VRDN",
    "VXX"
  ],
  "ETF (Sector)": [
    "ICLN",
    "JETS",
    "KRE",
    "KWEB",
    "URA",
    "XBI",
    "XLB",
    "XLC",
    "XLE",
    "XLF",
    "XLI",
    "XLK",
    "XLP",
    "XLU",
    "XLV",
    "XLY",
    "XOP",
    "XRT"
  ],
  "ETP (Crypto)": [
    "BITO",
    "BITX",
    "EETH",
    "ETH",
    "ETHA",
    "ETHD",
    "ETHE",
    "ETHT",
    "ETHZ",
    "FBTC",
    "GBTC",
    "IBIT"
  ],
  "Energy (Oil & Gas)": [
    "ACDC",
    "AESI",
    "AMPY",
    "APA",
    "AR",
    "BKV",
    "BTE",
    "CHRD",
    "CLB",
    "CNQ",
    "CRC",
    "CRGY",
    "CRK",
    "CTRA",
    "CVE",
    "DVN",
    "EC",
    "EOG",
    "EPSN",
    "EQT",
    "EXE",
    "FANG",
    "HAL",
    "HESM",
    "HP",
    "HPK",
    "KLXE",
    "KOS",
    "MGY",
    "NOG",
    "NUAI",
    "OBE",
    "OII",
    "OXY",
    "PBR",
    "RIG",
    "RRC",
    "SDRL",
    "SHEL",
    "SLB",
    "SM",
    "SOC",
    "TALO",
    "TTI",
    "VAL",
    "VIST",
    "VNOM",
    "VOC",
    "WDS",
    "WTTR",
    "XPRO"
  ],
  "Energy (Refining)": [
    "BP",
    "CLMT",
    "COP",
    "CVI",
    "CVX",
    "DK",
    "EQNR",
    "MPC",
    "PBF",
    "PSX",
    "SU",
    "VLO",
    "VVV",
    "XOM",
    "YPF"
  ],
  "Financials/Real Estate": [
    "AAMI",
    "ABCB",
    "ABR",
    "ABTC",
    "ACGL",
    "AEXA",
    "AFL",
    "AFRM",
    "AGNC",
    "AGQ",
    "AIFU",
    "AIG",
    "ALHC",
    "ALRS",
    "ALTS",
    "AMBR",
    "AMH",
    "AMP",
    "AMT",
    "ANY",
    "APO",
    "APPS",
    "ARBK",
    "ARE",
    "ARES",
    "ASB",
    "ASST",
    "AUB",
    "AXP",
    "BAC",
    "BAM",
    "BBAR",
    "BBT",
    "BCS",
    "BEKE",
    "BFST",
    "BHF",
    "BITF",
    "BK",
    "BKKT",
    "BLK",
    "BLSH",
    "BMNR",
    "BN",
    "BNL",
    "BRO",
    "BRR",
    "BSOL",
    "BTBT",
    "BTDR",
    "BUSE",
    "BWET",
    "BWIN",
    "BX",
    "C",
    "CAN",
    "CATY",
    "CBOE",
    "CBRE",
    "CBSH",
    "CCBG",
    "CDP",
    "CG",
    "CHMI",
    "CHYM",
    "CI",
    "CIA",
    "CIFR",
    "CLDT",
    "CLOV",
    "CLSK",
    "CME",
    "CMTG",
    "CNC",
    "CNO",
    "COF",
    "COIN",
    "COMP",
    "CORZ",
    "CPT",
    "CRCL",
    "CSR",
    "CTBI",
    "CTRE",
    "CUBE",
    "CWK",
    "CZNC",
    "DB",
    "DBRG",
    "DEI",
    "DFDV",
    "DGXX",
    "DLR",
    "DOUG",
    "EBC",
    "ECPG",
    "EGBN",
    "EHTH",
    "EIG",
    "ELME",
    "ELS",
    "EQBK",
    "EQIX",
    "ESNT",
    "ESS",
    "EZBC",
    "FFBC",
    "FFIN",
    "FG",
    "FGNX",
    "FHN",
    "FIGR",
    "FISI",
    "FLG",
    "FNF",
    "FRGE",
    "FSP",
    "FUTU",
    "FWDI",
    "GDOT",
    "GEMI",
    "GGAL",
    "GLXY",
    "GPMT",
    "GS",
    "HASI",
    "HIVE",
    "HLNE",
    "HOOD",
    "HOPE",
    "HR",
    "HRTG",
    "HSBC",
    "HST",
    "HTBK",
    "HUM",
    "HUT",
    "IBKR",
    "ICE",
    "INVH",
    "IREN",
    "IRM",
    "JEF",
    "JPM",
    "JRVR",
    "KKR",
    "LB",
    "LC",
    "LDI",
    "LINE",
    "LMND",
    "LNC",
    "LPRO",
    "LX",
    "LXP",
    "MAC",
    "MARA",
    "MC",
    "MCHB",
    "MIAX",
    "MOH",
    "MRP",
    "MRX",
    "MS",
    "MSTR",
    "MTG",
    "MUFG",
    "NAKA",
    "NDAQ",
    "NLY",
    "NRT",
    "NSA",
    "NTST",
    "NU",
    "OPAD",
    "OPEN",
    "OPRT",
    "ORBS",
    "ORC",
    "OSCR",
    "OWL",
    "PEB",
    "PGR",
    "PGY",
    "PKST",
    "PLD",
    "PNC",
    "PNFP",
    "QFIN",
    "RC",
    "RILY",
    "RIOT",
    "RKT",
    "RYAN",
    "RYN",
    "SAN",
    "SBCF",
    "SBET",
    "SCHW",
    "SIEB",
    "SKYH",
    "SLAI",
    "SLDE",
    "SLG",
    "SLM",
    "SLQT",
    "SMA",
    "SOFI",
    "SSRM",
    "SUIG",
    "SUPV",
    "SVC",
    "TBBK",
    "TFC",
    "TIGR",
    "TPG",
    "TWO",
    "UBSI",
    "UCB",
    "UNH",
    "UPST",
    "UPXI",
    "USB",
    "UWMC",
    "VNO",
    "WFC",
    "WNEB",
    "WRB",
    "WULF",
    "WY",
    "WYFI",
    "XP",
    "YRD"
  ],
  "Healthcare (Medical Devices)": [
    "ALC",
    "ALGN",
    "ANGO",
    "APT",
    "ATEC",
    "BAX",
    "BBNX",
    "BFLY",
    "BLFS",
    "BSX",
    "CLPT",
    "CNMD",
    "CODX",
    "CTSO",
    "CVRX",
    "DCTH",
    "DRIO",
    "DXCM",
    "EMBC",
    "ENOV",
    "ESTA",
    "EYE",
    "GEHC",
    "GKOS",
    "GMED",
    "HSDT",
    "HTFL",
    "INSP",
    "ISRG",
    "KRMD",
    "LFWD",
    "MBOT",
    "MDT",
    "MMM",
    "MYO",
    "NNOX",
    "NSPR",
    "NVST",
    "OBIO",
    "OM",
    "SGHT",
    "SKIN",
    "STAA",
    "STIM",
    "STSS",
    "STVN",
    "STXS",
    "TELA",
    "TMCI",
    "TMDX",
    "TNDM",
    "WRBY",
    "XAIR"
  ],
  "Healthcare (Pharma)": [
    "ABBV",
    "ABCL",
    "ABT",
    "ABVC",
    "ABVX",
    "ACAD",
    "ACB",
    "ACHV",
    "ACLX",
    "ACRS",
    "ACXP",
    "ADCT",
    "ADMA",
    "ADPT",
    "AGIO",
    "AKBA",
    "ALDX",
    "ALEC",
    "ALKS",
    "ALLO",
    "ALMS",
    "ALNY",
    "ALT",
    "ALXO",
    "AMGN",
    "AMLX",
    "AMRN",
    "ANAB",
    "ANNX",
    "ANRO",
    "ANVS",
    "APGE",
    "APLS",
    "AQST",
    "ARCT",
    "ARDX",
    "ARQT",
    "ASMB",
    "ATAI",
    "ATOS",
    "ATYR",
    "AUTL",
    "AVTX",
    "AXSM",
    "BBIO",
    "BCAB",
    "BCAX",
    "BCRX",
    "BEAM",
    "BHC",
    "BHVN",
    "BIIB",
    "BLRX",
    "BMEA",
    "BMRN",
    "BMY",
    "BNTC",
    "BTAI",
    "CABA",
    "CAPR",
    "CATX",
    "CCCC",
    "CELU",
    "CGC",
    "CGEM",
    "CGEN",
    "CMPS",
    "CNTA",
    "COGT",
    "CPIX",
    "CRBU",
    "CRDF",
    "CRMD",
    "CRON",
    "CRSP",
    "CRVS",
    "CTMX",
    "CTXR",
    "CVM",
    "CYRX",
    "CYTK",
    "DAWN",
    "DNA",
    "DNLI",
    "DNTH",
    "DYAI",
    "DYN",
    "EBS",
    "EDIT",
    "ELAN",
    "ELVN",
    "ENTA",
    "ENTX",
    "EOLS",
    "EQ",
    "ESPR",
    "EWTX",
    "EXEL",
    "FATE",
    "FBIO",
    "FDMT",
    "FHTX",
    "FULC",
    "GALT",
    "GERN",
    "GHRS",
    "GILD",
    "GLUE",
    "GMAB",
    "GOSS",
    "GPCR",
    "GSK",
    "HOWL",
    "HRMY",
    "HUMA",
    "HYFT",
    "IBRX",
    "IFRX",
    "IMMX",
    "IMNM",
    "IMRX",
    "INBX",
    "INDV",
    "INO",
    "INSM",
    "IOVA",
    "IRD",
    "IVVD",
    "JANX",
    "JAZZ",
    "JNJ",
    "JSPR",
    "KOD",
    "KPTI",
    "KROS",
    "KRRO",
    "KYTX",
    "LENZ",
    "LFCR",
    "LLY",
    "LNAI",
    "LNTH",
    "LQDA",
    "LRMR",
    "LTRN",
    "LXEO",
    "LXRX",
    "LYEL",
    "MBX",
    "MCRB",
    "MIRM",
    "MIST",
    "MLTX",
    "MLYS",
    "MNKD",
    "MRK",
    "MRNA",
    "MYGN",
    "NAGE",
    "NAMS",
    "NBP",
    "NEOG",
    "NGNE",
    "NKTX",
    "NMRA",
    "NNVC",
    "NRIX",
    "NRXP",
    "NTLA",
    "NUVB",
    "NVAX",
    "NVO",
    "OCUL",
    "OGN",
    "OLMA",
    "OMER",
    "ORGO",
    "ORKA",
    "OTLK",
    "PBYI",
    "PCRX",
    "PCVX",
    "PDSB",
    "PFE",
    "PGEN",
    "PLX",
    "PMVP",
    "PPBT",
    "PRAX",
    "PRGO",
    "PRLD",
    "PRME",
    "PROK",
    "PRPH",
    "PRQR",
    "PRTA",
    "PTCT",
    "PVLA",
    "QURE",
    "RANI",
    "RAPP",
    "RCKT",
    "REGN",
    "REPL",
    "RGC",
    "RIGL",
    "RLAY",
    "RLMD",
    "RMTI",
    "ROIV",
    "RVPH",
    "RXRX",
    "RZLT",
    "SANA",
    "SAVA",
    "SEPN",
    "SGMO",
    "SGMT",
    "SIGA",
    "SKYE",
    "SLN",
    "SLNO",
    "SLS",
    "SMMT",
    "SNDX",
    "SPRO",
    "SPRY",
    "SRPT",
    "SRRK",
    "STOK",
    "STRO",
    "SUPN",
    "SVRA",
    "SYRE",
    "TARA",
    "TARS",
    "TECH",
    "TECX",
    "TERN",
    "TEVA",
    "TGTX",
    "TLRY",
    "TNGX",
    "TNXP",
    "TNYA",
    "TRIB",
    "TRVI",
    "TSHA",
    "TVRD",
    "TWST",
    "UNCY",
    "UPB",
    "URGN",
    "VCEL",
    "VERA",
    "VERU",
    "VIR",
    "VKTX",
    "VNDA",
    "VOR",
    "VRTX",
    "VSTM",
    "VTYX",
    "VYGR",
    "WVE",
    "XENE",
    "XERS",
    "XFOR",
    "XNCR",
    "ZBIO",
    "ZLAB",
    "ZTS",
    "ZURA",
    "ZVRA"
  ],
  "Healthcare (Providers/Services)": [
    "AIRS",
    "AVAH",
    "BDSX",
    "BKD",
    "BTSG",
    "CAI",
    "CELC",
    "CYH",
    "DCGO",
    "FTRE",
    "GH",
    "GRAL",
    "HCSG",
    "HIMS",
    "LFMD",
    "LFST",
    "NTRA",
    "OPCH",
    "PACS",
    "PGNY",
    "PSNL",
    "RDNT",
    "SERA",
    "SGRY",
    "SRTA",
    "TDOC",
    "TOI",
    "UHS",
    "VCYT",
    "WGS",
    "XGN"
  ],
  "Manufacturing": [
    "A",
    "AA",
    "ABEV",
    "ABVE",
    "ACMR",
    "AEHR",
    "AGCO",
    "AIRJ",
    "ALB",
    "ALH",
    "ALTO",
    "AME",
    "AMPX",
    "AMRZ",
    "AMSC",
    "AMTX",
    "AOUT",
    "AP",
    "APD",
    "AQMS",
    "ARRY",
    "AS",
    "ASML",
    "ASPI",
    "ATER",
    "ATI",
    "AVD",
    "AVNT",
    "BC",
    "BE",
    "BG",
    "BIOX",
    "BIRK",
    "BLDP",
    "BLNK",
    "BNKK",
    "BOOM",
    "BRCC",
    "BRKR",
    "BRLT",
    "BUD",
    "BW",
    "BWEN",
    "BWXT",
    "BYND",
    "BYRN",
    "CAG",
    "CAL",
    "CAPT",
    "CAT",
    "CBAT",
    "CBUS",
    "CC",
    "CCU",
    "CE",
    "CELH",
    "CENX",
    "CF",
    "CGNX",
    "CHD",
    "CHPT",
    "CL",
    "CMC",
    "CMI",
    "CNH",
    "COCO",
    "CODI",
    "COHR",
    "COKE",
    "COLM",
    "CPB",
    "CR",
    "CRH",
    "CRI",
    "CROX",
    "CSL",
    "CSTM",
    "CSW",
    "CTAS",
    "CTKB",
    "CW",
    "CXT",
    "DAIO",
    "DAKT",
    "DE",
    "DECK",
    "DFLI",
    "DHR",
    "DOW",
    "DRS",
    "EAF",
    "ECL",
    "EL",
    "ELF",
    "EMR",
    "ENTG",
    "ENVX",
    "EOSE",
    "EPAC",
    "ERII",
    "ESI",
    "ETN",
    "EYPT",
    "FCEL",
    "FIGS",
    "FLNC",
    "FLO",
    "FLY",
    "FOSL",
    "FOXF",
    "FRPT",
    "FTI",
    "FTK",
    "GD",
    "GE",
    "GEOS",
    "GEV",
    "GGB",
    "GLW",
    "GNRC",
    "GNSS",
    "GOOS",
    "GPK",
    "GPRO",
    "GTES",
    "HII",
    "HLMN",
    "HOG",
    "HRL",
    "HSAI",
    "HSY",
    "HTOO",
    "HUN",
    "HWM",
    "HXL",
    "HY",
    "IFF",
    "ILMN",
    "IMAX",
    "IP",
    "ISPR",
    "ITP",
    "JBS",
    "JCI",
    "KDP",
    "KHC",
    "KLAC",
    "KMB",
    "KMT",
    "KO",
    "KODK",
    "KTOS",
    "KVUE",
    "LASE",
    "LEG",
    "LEVI",
    "LHX",
    "LMT",
    "LNZA",
    "LODE",
    "LOMA",
    "LPX",
    "LRCX",
    "LULU",
    "LUNR",
    "LW",
    "LWLG",
    "LYB",
    "LYTS",
    "MASS",
    "MAT",
    "MATV",
    "MBC",
    "MDLZ",
    "MEC",
    "MHK",
    "MIDD",
    "MIR",
    "MO",
    "MT",
    "MVST",
    "NKE",
    "NN",
    "NOMD",
    "NPWR",
    "NRGV",
    "NTR",
    "NWL",
    "NX",
    "OC",
    "ODD",
    "OI",
    "OLN",
    "ONON",
    "ORGN",
    "OUST",
    "OXM",
    "PACB",
    "PACK",
    "PCT",
    "PEP",
    "PG",
    "PII",
    "PLUG",
    "PM",
    "POST",
    "PPC",
    "PPG",
    "PPSI",
    "PRM",
    "PRMB",
    "PTON",
    "QS",
    "QSI",
    "QTRX",
    "RAIL",
    "RAL",
    "RDW",
    "RKLB",
    "RR",
    "RUN",
    "RVTY",
    "RYAM",
    "SEER",
    "SEI",
    "SENS",
    "SERV",
    "SES",
    "SHOO",
    "SLDP",
    "SLGN",
    "SLI",
    "SMR",
    "SNBR",
    "SOLS",
    "SONO",
    "SONY",
    "ST",
    "STZ",
    "SUZ",
    "SXC",
    "SYM",
    "TAP",
    "TER",
    "TEX",
    "TKR",
    "TMO",
    "TPR",
    "TREX",
    "TROX",
    "TS",
    "TSE",
    "TT",
    "TTC",
    "TWI",
    "TXG",
    "UA",
    "UAMY",
    "VFC",
    "VITL",
    "VOYG",
    "WBX",
    "WFRD",
    "WHD",
    "WLK",
    "WRAP",
    "WWD",
    "XXII",
    "YETI",
    "YSG"
  ],
  "Manufacturing (Aerospace)": [
    "ACHR",
    "AIR",
    "ATRO",
    "AVAV",
    "BA",
    "DPRO",
    "EH",
    "EVTL",
    "HON",
    "JOBY",
    "RTX",
    "SARO",
    "TXT"
  ],
  "Manufacturing (Automotive)": [
    "ADNT",
    "AEVA",
    "APTV",
    "BLBD",
    "CAAS",
    "CPS",
    "CVGI",
    "EMPD",
    "F",
    "FFAI",
    "GM",
    "GTX",
    "HYLN",
    "INVZ",
    "LCID",
    "LEA",
    "LI",
    "MGA",
    "MOD",
    "NIO",
    "OSK",
    "PATK",
    "PSNY",
    "RIVN",
    "SEV",
    "STLA",
    "TSLA",
    "VFS",
    "WKHS",
    "XPEV"
  ],
  "Media/Entertainment": [
    "AMC",
    "ANGX",
    "CNVS",
    "CURI",
    "FUBO",
    "IQ",
    "NFLX",
    "TOON"
  ],
  "Media/Publishing": [
    "TRI"
  ],
  "Mining": [
    "ABAT",
    "AEM",
    "AG",
    "AGI",
    "B",
    "BHP",
    "BTG",
    "BTU",
    "BVN",
    "CCJ",
    "CDE",
    "CLF",
    "CNR",
    "CRML",
    "DNN",
    "EQX",
    "ERO",
    "FCX",
    "GFI",
    "GROY",
    "GSM",
    "HBM",
    "HCC",
    "HL",
    "HMY",
    "HYMC",
    "IAG",
    "IDR",
    "IE",
    "KGC",
    "LAC",
    "LGO",
    "METC",
    "MP",
    "MUX",
    "NAK",
    "NB",
    "NEM",
    "NEWP",
    "NG",
    "NVA",
    "NXE",
    "ODV",
    "ORLA",
    "PAAS",
    "SA",
    "SCCO",
    "SGML",
    "SKE",
    "SQM",
    "SVM",
    "TECK",
    "TGB",
    "TMC",
    "TMQ",
    "UEC",
    "USAR",
    "USAS",
    "USAU",
    "UUUU",
    "VALE",
    "VMC",
    "WPM",
    "WWR"
  ],
  "Other/Services": [
    "ABM",
    "ABNB",
    "ABSI",
    "ACEL",
    "ACN",
    "ACVA",
    "ADV",
    "AKAM",
    "AMTM",
    "ANGI",
    "APG",
    "BABA",
    "BAH",
    "BATRA",
    "BGSF",
    "BRSL",
    "CAR",
    "CART",
    "CHGG",
    "CHH",
    "CNXC",
    "CRL",
    "CSGP",
    "CZR",
    "DASH",
    "DHX",
    "DIS",
    "DKNG",
    "DLO",
    "EBAY",
    "ETSY",
    "EVGO",
    "FIS",
    "FLL",
    "FTAI",
    "FUN",
    "GETY",
    "GPN",
    "GRAB",
    "GRPN",
    "HGV",
    "HLT",
    "HQY",
    "HTZ",
    "INCY",
    "IT",
    "KLC",
    "LTH",
    "LUCK",
    "LVS",
    "LYFT",
    "MA",
    "MAN",
    "MANU",
    "MAR",
    "MAX",
    "MELI",
    "MGM",
    "MLCO",
    "MMS",
    "MNY",
    "MSCI",
    "MXCT",
    "NCMI",
    "NEO",
    "NOTE",
    "NOTV",
    "NRDY",
    "NSP",
    "PAY",
    "PAYO",
    "PDD",
    "PENN",
    "PK",
    "PLNT",
    "PRKS",
    "PSFE",
    "PSQH",
    "PYPL",
    "RELY",
    "RHI",
    "RSI",
    "RSKD",
    "SE",
    "SGHC",
    "SHO",
    "SPGI",
    "STUB",
    "TAL",
    "TIC",
    "TNL",
    "TONX",
    "TSSI",
    "TTEK",
    "UBER",
    "UDMY",
    "UPBD",
    "URI",
    "V",
    "WH",
    "WMG",
    "WSC",
    "WW",
    "WYNN",
    "XPOF",
    "YELP",
    "YQ",
    "ZG"
  ],
  "Technology (Computers/Hardware)": [
    "AAPL",
    "ANET",
    "CSCO",
    "DELL",
    "DGII",
    "EVLV",
    "EXTR",
    "FFIV",
    "FTNT",
    "HPE",
    "HPQ",
    "IBM",
    "NTAP",
    "OMCL",
    "OSS",
    "PANW",
    "SMCI",
    "SNDK",
    "STX",
    "WDC",
    "ZEPP"
  ],
  "Technology (Semiconductors/Electronics)": [
    "AAOI",
    "ADI",
    "ALAB",
    "ALGM",
    "ALMU",
    "AMAT",
    "AMBA",
    "AMD",
    "AMPG",
    "AOSL",
    "APH",
    "ARM",
    "ASX",
    "ATOM",
    "AUDC",
    "AVGO",
    "AXTI",
    "BKSY",
    "CIEN",
    "CLS",
    "CMBM",
    "CMTL",
    "CRDO",
    "CRNT",
    "CSIQ",
    "ENPH",
    "FLEX",
    "FN",
    "FSLR",
    "FTCI",
    "GSIT",
    "HIMX",
    "INDI",
    "INSG",
    "INTC",
    "KLIC",
    "KOPN",
    "KULR",
    "LAES",
    "LASR",
    "LITE",
    "LPTH",
    "LSCC",
    "MAXN",
    "MCHP",
    "MEI",
    "MRVL",
    "MU",
    "MVIS",
    "MX",
    "MXL",
    "NEON",
    "NOK",
    "NVDA",
    "NVTS",
    "NXPI",
    "OLED",
    "ON",
    "ONDS",
    "PENG",
    "PI",
    "PL",
    "PLAB",
    "POET",
    "POWI",
    "QCOM",
    "QRVO",
    "SANM",
    "SATL",
    "SEDG",
    "SHLS",
    "SKYT",
    "SMTC",
    "SQNS",
    "STM",
    "SWKS",
    "SYNA",
    "TE",
    "TSM",
    "TTMI",
    "TXN",
    "UMAC",
    "UMC",
    "VIAV",
    "VREX",
    "VRT",
    "VSH",
    "VUZI",
    "WATT",
    "WOLF"
  ],
  "Technology (Software)": [
    "ADBE",
    "ADP",
    "ADSK",
    "AEYE",
    "AGYS",
    "AI",
    "AISP",
    "ALKT",
    "API",
    "APLD",
    "APP",
    "APPF",
    "APPN",
    "ARBE",
    "ARQQ",
    "ASAN",
    "ASUR",
    "AUR",
    "AVPT",
    "BAND",
    "BB",
    "BBAI",
    "BIDU",
    "BILI",
    "BILL",
    "BL",
    "BLZE",
    "BMBL",
    "BRAG",
    "BRZE",
    "BSY",
    "CARG",
    "CARS",
    "CCLD",
    "CCSI",
    "CDLX",
    "CDNS",
    "CFLT",
    "CGNT",
    "CINT",
    "CLVT",
    "CMRC",
    "CRM",
    "CRNC",
    "CRWD",
    "CRWV",
    "CVLT",
    "CWAN",
    "CXAI",
    "CXM",
    "DBX",
    "DCBO",
    "DDD",
    "DDOG",
    "DH",
    "DJT",
    "DMRC",
    "DOCN",
    "DOCS",
    "DOCU",
    "DSGX",
    "DSP",
    "DUOL",
    "DV",
    "EA",
    "EGHT",
    "ESTC",
    "EVTC",
    "FDS",
    "FIG",
    "FIVN",
    "FLUT",
    "FNGR",
    "FROG",
    "FRSH",
    "FSLY",
    "GDDY",
    "GDRX",
    "GDS",
    "GLBE",
    "GMGI",
    "GOOG",
    "GOOGL",
    "GRND",
    "GRRR",
    "GTLB",
    "GTM",
    "GWRE",
    "HCAT",
    "HNGE",
    "HUBS",
    "IAC",
    "INFY",
    "INOD",
    "INTU",
    "IONQ",
    "IOT",
    "KC",
    "KD",
    "KDK",
    "LDOS",
    "LIF",
    "LPSN",
    "LZ",
    "MBLY",
    "MDB",
    "META",
    "MSFT",
    "MTLS",
    "NBIS",
    "NCNO",
    "NET",
    "NOW",
    "NTNX",
    "NTSK",
    "OKTA",
    "ORCL",
    "PATH",
    "PAYC",
    "PCTY",
    "PD",
    "PDYN",
    "PEGA",
    "PHUN",
    "PINS",
    "PLTR",
    "PONY",
    "PRCH",
    "PUBM",
    "QBTS",
    "QTWO",
    "QUBT",
    "RBLX",
    "RBRK",
    "RCAT",
    "RDDT",
    "RDNW",
    "RGTI",
    "RNG",
    "RPD",
    "RUM",
    "RXT",
    "RZLV",
    "S",
    "SABR",
    "SAIC",
    "SAIL",
    "SAP",
    "SHOP",
    "SLP",
    "SMSI",
    "SNAP",
    "SNOW",
    "SNPS",
    "SOGP",
    "SOUN",
    "SPT",
    "SRAD",
    "STEM",
    "STNE",
    "SY",
    "TDC",
    "TEAD",
    "TEAM",
    "TEM",
    "TENB",
    "TLS",
    "TOST",
    "TRIP",
    "TTAN",
    "TTD",
    "TTWO",
    "TUYA",
    "TWLO",
    "U",
    "UPWK",
    "VERI",
    "VERX",
    "VNET",
    "VRAR",
    "VRNS",
    "WAY",
    "WDAY",
    "WEAV",
    "WIT",
    "WRD",
    "XNET",
    "XYZ",
    "YEXT",
    "YYAI",
    "ZENA",
    "ZETA",
    "ZIP",
    "ZM",
    "ZS"
  ],
  "Transportation": [
    "AAL",
    "ALK",
    "BKNG",
    "CCEC",
    "CCL",
    "CMBT",
    "CNI",
    "CP",
    "CSX",
    "CUK",
    "DAL",
    "DINO",
    "EXPE",
    "FDX",
    "FIP",
    "FLNG",
    "FRO",
    "FWRD",
    "GBTG",
    "GLNG",
    "HUBG",
    "JBLU",
    "KEX",
    "LUV",
    "MMYT",
    "NAT",
    "NCLH",
    "NSC",
    "NVGS",
    "OMEX",
    "PAA",
    "RCL",
    "RXO",
    "RYAAY",
    "SMHI",
    "SNCY",
    "SOBO",
    "SPCE",
    "STNG",
    "TEN",
    "TORO",
    "UAL",
    "ULCC",
    "UNP",
    "UPS",
    "VIK",
    "WERN",
    "ZIM"
  ],
  "Unknown": [
    "AAPU",
    "AGIX",
    "AIRR",
    "AIYY",
    "AMDL",
    "AMZW",
    "AMZZ",
    "APLT",
    "ARKG",
    "ARKK",
    "ARKW",
    "ASHR",
    "ASTX",
    "ATHA",
    "AVGG",
    "AVGX",
    "AVL",
    "AVMV",
    "AVUV",
    "AXL",
    "AZYY",
    "BABX",
    "BAGY",
    "BAIG",
    "BBH",
    "BBJP",
    "BCD",
    "BCSF",
    "BEDZ",
    "BETZ",
    "BITY",
    "BLCN",
    "BMNG",
    "BOND",
    "BOTZ",
    "BSV",
    "BTAL",
    "BTCL",
    "BUG",
    "BULU",
    "BUZZ",
    "BXSL",
    "CADE",
    "CASI",
    "CCCX",
    "CCOR",
    "CIVI",
    "CLSX",
    "CMPO",
    "CNBS",
    "COMM",
    "CONI",
    "CONL",
    "CORO",
    "CRCA",
    "CRCD",
    "CRWG",
    "CRWU",
    "CSD",
    "CVAC",
    "CWVX",
    "CYBN",
    "DBEF",
    "DFAS",
    "DFIP",
    "DFUV",
    "DGRS",
    "DISV",
    "DIVI",
    "DJTU",
    "DLN",
    "DMAT",
    "DOL",
    "DPST",
    "DRN",
    "DTCR",
    "DUHP",
    "DUSA",
    "DVAX",
    "EBIZ",
    "ECH",
    "EFAV",
    "ENPX",
    "ESGV",
    "ETHU",
    "EUFN",
    "EVMT",
    "EWM",
    "EWZS",
    "FDEM",
    "FDIS",
    "FDVV",
    "FEM",
    "FENI",
    "FEZ",
    "FHEQ",
    "FIGG",
    "FLAX",
    "FMET",
    "FNX",
    "FPE",
    "FPWR",
    "FSK",
    "FTXR",
    "FV",
    "FYBR",
    "GES",
    "GLGG",
    "GLXU",
    "HIBL",
    "HIBS",
    "HIMZ",
    "HOOX",
    "HOUS",
    "INTW",
    "IONX",
    "IONZ",
    "IRE",
    "IREX",
    "JAMF",
    "KYN",
    "LABX",
    "MAGS",
    "METU",
    "MNMD",
    "MNRS",
    "MODG",
    "MPW",
    "MRAL",
    "MRSN",
    "MSOS",
    "MULL",
    "NAIL",
    "NAN",
    "NBIG",
    "NINE",
    "NVTX",
    "OMI",
    "PCH",
    "PLTU",
    "PSEC",
    "PXIU",
    "QPUX",
    "QUBX",
    "REVG",
    "RGTU",
    "RIOX",
    "RKLX",
    "ROBN",
    "SBIT",
    "SMCL",
    "SMCX",
    "SMH",
    "SMLR",
    "SMST",
    "SMU",
    "SOFX",
    "SOLT",
    "SOXX",
    "TARK",
    "THS",
    "TRUE",
    "TSDD",
    "TSLG",
    "TSLR",
    "ULTY",
    "URTY",
    "USD",
    "WEBL",
    "WGMI",
    "XRPT",
    "YINN"
  ],
  "Utilities": [
    "AEE",
    "AES",
    "AM",
    "AQN",
    "BEPC",
    "CDZI",
    "CEG",
    "CEPU",
    "CLNE",
    "CMS",
    "CTRI",
    "CWEN",
    "CWST",
    "D",
    "EIX",
    "EPD",
    "ES",
    "ET",
    "FTS",
    "KGS",
    "KMI",
    "KNTK",
    "LNG",
    "MNTK",
    "NEE",
    "NEXT",
    "NFE",
    "NFG",
    "NNE",
    "NRG",
    "OKLO",
    "OPTT",
    "ORA",
    "PCG",
    "QRHC",
    "SBS",
    "SMC",
    "SO",
    "SPRU",
    "TLN",
    "TRP",
    "VG",
    "VST",
    "VVPR",
    "WMB",
    "WTRG"
  ],
  "Wholesale": [
    "AIT",
    "ASH",
    "ASPN",
    "CAH",
    "CENT",
    "COSM",
    "DPZ",
    "DXPE",
    "FERG",
    "GPC",
    "HFFG",
    "HLF",
    "LKQ",
    "MCK",
    "QXO",
    "RELL",
    "TEL",
    "UGRO",
    "VSTS",
    "WKC"
  ]
};

export default function LiveWatchlist() {
  const [query, setQuery] = useState("");
  const [collapsed, setCollapsed] = useState<Record<string, boolean>>({});
  const [collapseAll, setCollapseAll] = useState(false);

  const [quickIndustry, setQuickIndustry] = useState<string | null>(null);

  const [view, setView] = useState<"comfortable" | "compact">("comfortable");
  const [activeOnly, setActiveOnly] = useState(false); // optional future use
  const [toast, setToast] = useState<string | null>(null);
  const [selected, setSelected] = useState<{ symbol: string; industry: string } | null>(null);
  const showTop = useScrollTopButton();
  const [etfOnly, setEtfOnly] = useState(false);
  const [sortMode, setSortMode] = useState<"size" | "az">("size");

  useEffect(() => {
    if (!toast) return;
    const id = window.setTimeout(() => setToast(null), 1400);
    return () => window.clearTimeout(id);
  }, [toast]);

  async function copyToClipboard(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      setToast(`Copied ${text}`);
    } catch {
      // fallback
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setToast(`Copied ${text}`);
    }
  }

  // sanitize: normalize symbols + dedupe once (defensive, though GROUPS is already clean)
  const groups = useMemo(() => {
    const cleaned: IndustryGroups = {};
    for (const [industry, syms] of Object.entries(GROUPS || {})) {
      const seen = new Set<string>();
      const out: string[] = [];
      for (const raw of syms || []) {
        const s = normalizeSymbol(raw);
        if (!s || seen.has(s)) continue;
        seen.add(s);
        out.push(s);
      }
      cleaned[industry || "Unknown"] = out.sort((a, b) => a.localeCompare(b));
    }
    return cleaned;
  }, []);

  const totalSymbols = useMemo(() => {
    const all = Object.values(groups).flat();
    return new Set(all).size;
  }, [groups]);

  
  const groupedFiltered = useMemo(() => {
    const q = query.trim().toUpperCase();
    const out: { industry: string; symbols: string[] }[] = [];

    for (const [industry, syms] of Object.entries(groups)) {
      if (etfOnly && !(industry.startsWith("ETF") || industry.startsWith("ETP"))) continue;
      if (quickIndustry && industry !== quickIndustry) continue;

      const industryMatch = !q || industry.toUpperCase().includes(q);
      const symbols = !q ? syms : syms.filter((s) => industryMatch || s.includes(q));

      if (symbols.length) out.push({ industry, symbols });
    }

    // sort: size or A→Z; keep Unknown near bottom
    out.sort((a, b) => {
      if (a.industry === "Unknown" && b.industry !== "Unknown") return 1;
      if (b.industry === "Unknown" && a.industry !== "Unknown") return -1;
      if (sortMode === "az") return a.industry.localeCompare(b.industry);
      return b.symbols.length - a.symbols.length || a.industry.localeCompare(b.industry);
    });

    return out;
  }, [groups, query, quickIndustry, etfOnly, sortMode]);

  const topIndustries = useMemo(() => {
    const arr = Object.entries(groups)
      .map(([industry, syms]) => ({ industry, n: syms.length }))
      .sort((a, b) => b.n - a.n);
    // Show top 8 quick filters, keep Unknown last if it appears
    const top = arr.filter((x) => x.industry !== "Unknown").slice(0, 8);
    const unk = arr.find((x) => x.industry === "Unknown");
    if (unk) top.push(unk);
    return top;
  }, [groups]);


  useEffect(() => {
    setCollapsed((prev) => {
      const next = { ...prev };
      for (const g of groupedFiltered) next[g.industry] = collapseAll;
      return next;
    });
  }, [collapseAll, groupedFiltered]);

  return (
    <div className="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden">
      {/* Top gradient header */}
      <div className="relative p-6 border-b border-slate-100 bg-gradient-to-br from-slate-50 via-white to-slate-50">
        <div className="absolute inset-0 pointer-events-none opacity-[0.35]"
             style={{ backgroundImage: "radial-gradient(circle at 20% 20%, rgba(99,102,241,0.18), transparent 45%), radial-gradient(circle at 80% 30%, rgba(16,185,129,0.16), transparent 42%), radial-gradient(circle at 60% 80%, rgba(244,63,94,0.12), transparent 45%), linear-gradient(to right, rgba(15,23,42,0.04) 1px, transparent 1px), linear-gradient(to bottom, rgba(15,23,42,0.04) 1px, transparent 1px)" , backgroundSize: "auto, auto, auto, 48px 48px, 48px 48px" }} />
        <div className="relative flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div>
            <h1 className="text-2xl font-semibold text-slate-900 mb-1 tracking-tight">Live Watchlist</h1>
            <p className="text-xs text-slate-600">
              Loaded {totalSymbols} symbols across {Object.keys(groups).length} industry groups.
              <span className="ml-2 text-slate-400">•</span>
              <span className="ml-2 text-slate-500">Click a ticker to copy.</span>
            </p>
          </div>

          <div className="flex flex-col sm:items-end gap-3 w-full sm:w-[520px]">
            <div className="flex gap-2 w-full">
              <div className="flex-1">
                <label className="sr-only">Search</label>
                <input
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  placeholder="Search symbol or industry…"
                  className="w-full rounded-2xl border border-slate-200 bg-white/80 px-4 py-2.5 text-sm text-slate-900 outline-none focus:ring-4 focus:ring-slate-200/60"
                />
              </div>

              <button
                onClick={() => setCollapseAll((v) => !v)}
                className="rounded-2xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm text-slate-700 hover:bg-white transition"
                title={collapseAll ? "Expand all" : "Collapse all"}
              >
                {collapseAll ? "Expand" : "Collapse"}
              </button>

              <button
                onClick={() => setView((v) => (v === "comfortable" ? "compact" : "comfortable"))}
                className="rounded-2xl border border-slate-200 bg-white/80 px-3 py-2.5 text-sm text-slate-700 hover:bg-white transition"
                title={view === "comfortable" ? "Switch to compact" : "Switch to comfortable"}
              >
                {view === "comfortable" ? "Compact" : "Comfort"}
              </button>

            <div className="flex flex-wrap items-center justify-between gap-2 w-full">
              <div className="flex flex-wrap items-center gap-2">
                <button
                  onClick={() => { setQuery(""); setQuickIndustry(null); setEtfOnly(false); }}
                  className="text-[12px] px-3 py-1.5 rounded-full border border-slate-200 bg-white/80 hover:bg-white transition"
                  title="Clear filters"
                >
                  Reset
                </button>

                <button
                  onClick={() => setEtfOnly((v) => !v)}
                  className={cn(
                    "text-[12px] px-3 py-1.5 rounded-full border transition",
                    etfOnly ? "bg-slate-900 text-white border-slate-900" : "bg-white/80 text-slate-700 border-slate-200 hover:bg-white"
                  )}
                  title="Show only ETF/ETP groups"
                >
                  {etfOnly ? "ETFs: On" : "ETFs: Off"}
                </button>

                <button
                  onClick={() => setSortMode((v) => (v === "size" ? "az" : "size"))}
                  className="text-[12px] px-3 py-1.5 rounded-full border border-slate-200 bg-white/80 hover:bg-white transition"
                  title="Toggle sorting"
                >
                  Sort: {sortMode === "size" ? "Size" : "A→Z"}
                </button>
              </div>

              <div className="text-[11px] text-slate-600">
                Tip: right‑click a ticker to pin it without copying.
              </div>
            </div>

            </div>

            <div className="flex flex-wrap items-center gap-2 w-full">
              <button
                onClick={() => setQuickIndustry(null)}
                className={cn(
                  "text-[12px] px-3 py-1.5 rounded-full border transition",
                  !quickIndustry ? "bg-slate-900 text-white border-slate-900" : "bg-white/80 text-slate-700 border-slate-200 hover:bg-white"
                )}
              >
                All
              </button>
              {topIndustries.map((x) => {
                const t = themeForKey(x.industry);
                const active = quickIndustry === x.industry;
                return (
                  <button
                    key={x.industry}
                    onClick={() => setQuickIndustry((cur) => (cur === x.industry ? null : x.industry))}
                    className={cn(
                      "text-[12px] px-3 py-1.5 rounded-full border transition flex items-center gap-2",
                      active ? "shadow-sm" : "hover:shadow-sm"
                    )}
                    style={{
                      backgroundColor: active ? t.bg : "rgba(255,255,255,0.75)",
                      borderColor: active ? t.border : "rgba(226,232,240,1)",
                      color: "rgba(15,23,42,0.85)",
                    }}
                    title={x.industry}
                  >
                    <span className="truncate max-w-[160px]">{x.industry}</span>
                    <span className="text-[11px] px-2 py-0.5 rounded-full"
                          style={{ backgroundColor: "rgba(15,23,42,0.06)" }}>
                      {x.n}
                    </span>
                  </button>
                );
              })}
            </div>

            <div className="text-[11px] text-slate-600">
              Showing <span className="font-semibold text-slate-800">
                {groupedFiltered.reduce((acc, g) => acc + g.symbols.length, 0)}
              </span>{" "}
              / <span className="font-semibold text-slate-800">{totalSymbols}</span> symbols
              {quickIndustry ? <span className="ml-2 text-slate-500">• Filter: {quickIndustry}</span> : null}
            </div>
          </div>
        </div>
      </div>

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-5 left-1/2 -translate-x-1/2 z-50">
          <div className="px-4 py-2 rounded-2xl bg-slate-900 text-white text-sm shadow-lg">
            {toast}
          </div>
        </div>
      )}

      {/* Selected ticker mini-panel */}
      {selected && (
        <div className="px-6 py-3 border-b border-slate-100 bg-white">
          <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-3 min-w-0">
                  <div className="mt-0.5 h-10 w-1.5 rounded-full"
                       style={{ backgroundColor: theme.border }} />
                  <div className="min-w-0">
                    <h2 className="text-sm font-semibold text-slate-900 leading-5">
                      <Highlight text={g.industry} query={query} />
                    </h2>
                    <div className="mt-1 flex items-center gap-2 text-[11px] text-slate-600">
                      <span
                        className="px-2 py-0.5 rounded-full border"
                        style={{
                          backgroundColor: "rgba(255,255,255,0.6)",
                          borderColor: theme.border,
                          color: "rgba(15,23,42,0.75)",
                        }}
                      >
                        {g.symbols.length} tickers
                      </span>
                      <span className="text-slate-300">•</span>
                      <span className="truncate">
                        Click to copy • Right‑click to pin
                      </span>
                    </div>
                  </div>
                </div>

                <div className="flex items-center gap-2 shrink-0">
                  <button
                    onClick={() => copyToClipboard(g.symbols.join(", "))}
                    className="text-xs px-3 py-1.5 rounded-xl border bg-white/70 hover:bg-white transition"
                    style={{ borderColor: theme.border }}
                    title="Copy all tickers in this group"
                  >
                    Copy all
                  </button>

                  <button
                    onClick={() =>
                      setCollapsed((prev) => ({ ...prev, [g.industry]: !isCollapsed }))
                    }
                    className="text-xs px-3 py-1.5 rounded-xl border bg-white/70 hover:bg-white transition flex items-center gap-2"
                    style={{ borderColor: theme.border }}
                    aria-expanded={!isCollapsed}
                  >
                    {isCollapsed ? "Show" : "Hide"}
                    <Chevron open={!isCollapsed} />
                  </button>
                </div>
              </div>

              {!isCollapsed && (
                <div className={cn("mt-3 grid gap-2", view === "compact" ? "grid-cols-3 sm:grid-cols-5 md:grid-cols-7 lg:grid-cols-10 xl:grid-cols-12" : "grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8")}>
                  {g.symbols.map((sym) => (
                    <button
                      key={`${g.industry}:${sym}`}
                      type="button"
                      onClick={() => { setSelected({ symbol: sym, industry: g.industry }); copyToClipboard(sym); }}
                      onContextMenu={(e) => { e.preventDefault(); setSelected({ symbol: sym, industry: g.industry }); }}
                      className={cn("select-none rounded-[18px] border px-3 py-2 text-sm font-semibold tracking-wide text-center transition will-change-transform", view === "compact" ? "py-1.5 text-[13px]" : "py-2 text-sm", "hover:shadow-sm hover:-translate-y-[1px] active:translate-y-0")}
                      style={{
                        backgroundColor: theme.chipBg,
                        borderColor: theme.chipBorder,
                        color: theme.chipText,
                      }}
                      title={`${sym} • ${g.industry}`}
                    >
                      <Highlight text={sym} query={query} />
                    </button>
                  ))}
                </div>
              )}
            </section>
          );
        })}
      
      {showTop && (
        <button
          onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}
          className="fixed bottom-5 right-5 z-50 rounded-2xl border border-slate-200 bg-white/90 backdrop-blur px-4 py-3 text-sm text-slate-800 shadow-lg hover:shadow-xl transition"
          title="Back to top"
        >
          ↑ Top
        </button>
      )}

</div>
    </div>
  );
}
